import './globals.scss';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import { ApolloClientProvider } from './ApolloClientProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <div>
            <Link href="/">Home</Link>
            <Link href="/animals">Animals</Link>
            <Link href="/animals/dashboard">Animal Dashboard</Link>
          </div>
        </nav>
        <ApolloClientProvider>
          <main>{children}</main>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
